# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(655, 580)
        Admin.setStyleSheet("background-color: rgb(51, 51, 51);")  # Background color
        Admin.move(0,0)

        # Button to add a movie
        self.pushButton_add_movie = QtWidgets.QPushButton(Admin)
        self.pushButton_add_movie.setGeometry(QtCore.QRect(150, 260, 360, 39))
        self.pushButton_add_movie.setStyleSheet(
            """
            QPushButton {
                background-color: white;
                color: black;
                font-size: 18px;
                border-radius: 10px;
            }
            """
        )
        self.pushButton_add_movie.setObjectName("pushButton_add_movie")

        # Button to delete a movie
        self.pushButton_delete_movie = QtWidgets.QPushButton(Admin)
        self.pushButton_delete_movie.setGeometry(QtCore.QRect(150, 320, 360, 39))
        self.pushButton_delete_movie.setStyleSheet(
            """
            QPushButton {
                background-color: white;
                color: black;
                font-size: 18px;
                border-radius: 10px;
            }
            """
        )
        self.pushButton_delete_movie.setObjectName("pushButton_delete_movie")

        # Button to sign out
        self.pushButton_sign_out = QtWidgets.QPushButton(Admin)
        self.pushButton_sign_out.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.pushButton_sign_out.setStyleSheet(
            """
            QPushButton {
                background-color: white;
                color: black;
                font-size: 18px;
                border-radius: 10px;
            }
            """
        )
        self.pushButton_sign_out.setObjectName("pushButton_sign_out")

        # Input fields for movie title and schedule
        self.splitter_2 = QtWidgets.QSplitter(Admin)
        self.splitter_2.setGeometry(QtCore.QRect(90, 140, 471, 51))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")

        self.lineEdit_film_title = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_film_title.setStyleSheet(
            """
            QLineEdit {
                border-radius: 10px;
                font-size: 20px;
                background-color: white;
            }
            """
        )
        self.lineEdit_film_title.setText("")
        self.lineEdit_film_title.setObjectName("lineEdit_film_title")

        self.lineEdit_film_time = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_film_time.setStyleSheet(
            """
            QLineEdit {
                border-radius: 10px;
                font-size: 20px;
                background-color: white;
            }
            """
        )
        self.lineEdit_film_time.setText("")
        self.lineEdit_film_time.setObjectName("lineEdit_film_time")

        # Labels for movie title and schedule
        self.label_movie_title_admin = QtWidgets.QLabel(Admin)
        self.label_movie_title_admin.setGeometry(QtCore.QRect(150, 100, 131, 31))
        self.label_movie_title_admin.setStyleSheet(
            """
            QLabel {
                color: #FFFFFF;
                font-size: 22px;
            }
            """
        )
        self.label_movie_title_admin.setObjectName("label_movie_title_admin")

        self.label_movi_schedule_admin = QtWidgets.QLabel(Admin)
        self.label_movi_schedule_admin.setGeometry(QtCore.QRect(370, 100, 151, 31))
        self.label_movi_schedule_admin.setStyleSheet(
            """
            QLabel {
                color: #FFFFFF;
                font-size: 22px;
            }
            """
        )
        self.label_movi_schedule_admin.setObjectName("label_movi_schedule_admin")

        # Setup UI text
        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "Admin Panel"))
        self.pushButton_add_movie.setText(_translate("Admin", "Add movie"))
        self.pushButton_delete_movie.setText(_translate("Admin", "Delete movie"))
        self.pushButton_sign_out.setText(_translate("Admin", "SIGN OUT"))
        self.label_movie_title_admin.setText(_translate("Admin", "Movie title"))
        self.label_movi_schedule_admin.setText(_translate("Admin", "Movie schedule"))


