# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_history(object):
    def setupUi(self, user_history):
        # Основная настройка окна
        user_history.setObjectName("user_history")
        user_history.resize(655, 580)
        user_history.setStyleSheet("background-color: rgb(51, 51, 51);")

        # Заголовок "User's history"
        self.label_user_history = QtWidgets.QLabel(user_history)
        self.label_user_history.setGeometry(QtCore.QRect(250, 40, 1310, 31))
        self.label_user_history
        self.label_user_history.setStyleSheet(
            "color: white; font-size: 22px;"
        )
        self.label_user_history.setObjectName("label_user_history")

        # Метки "Movie", "Time", "Seat(s)"
        self.label_movie_title_main = QtWidgets.QLabel(user_history)
        self.label_movie_title_main.setGeometry(QtCore.QRect(130, 100, 131, 31))
        self.label_movie_title_main.setStyleSheet(
            "color: #FFFFFF; font-size: 22px;"
        )
        self.label_movie_title_main.setObjectName("label_movie_title_main")

        self.label_movie_title_main_2 = QtWidgets.QLabel(user_history)
        self.label_movie_title_main_2.setGeometry(QtCore.QRect(290, 100, 131, 31))
        self.label_movie_title_main_2.setStyleSheet(
            "color: #FFFFFF; font-size: 22px;"
        )
        self.label_movie_title_main_2.setObjectName("label_movie_title_main_2")

        self.label_movie_title_main_3 = QtWidgets.QLabel(user_history)
        self.label_movie_title_main_3.setGeometry(QtCore.QRect(450, 100, 131, 31))
        self.label_movie_title_main_3.setStyleSheet(
            "color: #FFFFFF; font-size: 22px;"
        )
        self.label_movie_title_main_3.setObjectName("label_movie_title_main_3")

        # Списки для отображения информации
        self.listWidget_seat = QtWidgets.QListWidget(user_history)
        self.listWidget_seat.setGeometry(QtCore.QRect(410, 140, 151, 300))
        self.listWidget_seat.setStyleSheet(
            "QListWidget {"
            "background-color: white; color: black; font-size: 18px; border-radius: 10px;"
            "}"
        )
        self.listWidget_seat.setObjectName("listWidget_seat")

        self.listWidget_time = QtWidgets.QListWidget(user_history)
        self.listWidget_time.setGeometry(QtCore.QRect(250, 140, 151, 300))
        self.listWidget_time.setStyleSheet(
            "QListWidget {"
            "background-color: white; color: black; font-size: 18px; border-radius: 10px;"
            "}"
        )
        self.listWidget_time.setObjectName("listWidget_time")

        self.listWidget_movie = QtWidgets.QListWidget(user_history)
        self.listWidget_movie.setGeometry(QtCore.QRect(90, 140, 151, 300))
        self.listWidget_movie.setStyleSheet(
            "QListWidget {"
            "background-color: white; color: black; font-size: 18px; border-radius: 10px;"
            "}"
        )
        self.listWidget_movie.setObjectName("listWidget_movie")

        # Установка текста и подключение слотов
        self.retranslateUi(user_history)
        QtCore.QMetaObject.connectSlotsByName(user_history)

    def retranslateUi(self, user_history):
        _translate = QtCore.QCoreApplication.translate
        user_history.setWindowTitle(_translate("user_history", "Form"))
        self.label_user_history.setText(_translate("user_history", "User's history"))
        self.label_movie_title_main.setText(_translate("user_history", "Movie"))
        self.label_movie_title_main_2.setText(_translate("user_history", "Time"))
        self.label_movie_title_main_3.setText(_translate("user_history", "Seat(s)"))
        self.listWidget_seat.setToolTip(
            _translate("user_history", "<html><head/><body><p>kjhkj</p></body></html>")
        )
        self.listWidget_time.setToolTip(
            _translate("user_history", "<html><head/><body><p>kjhkj</p></body></html>")
        )
        self.listWidget_movie.setToolTip(
            _translate("user_history", "<html><head/><body><p>kjhkj</p></body></html>")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    user_history = QtWidgets.QWidget()
    ui = Ui_user_history()
    ui.setupUi(user_history)
    user_history.show()
    sys.exit(app.exec_())
