# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info(object):
    def setupUi(self, info):
        # Set up the main window properties
        info.setObjectName("info")
        info.resize(655, 580)
        info.setStyleSheet("background-color: rgb(51, 51, 51);")  # Dark background color

        # Movie Name Label
        self.label_movi_name = QtWidgets.QLabel(info)
        self.label_movi_name.setGeometry(QtCore.QRect(80, 60, 131, 31))
        self.label_movi_name.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_movi_name.setObjectName("label_movi_name")

        # People Label
        self.label_people = QtWidgets.QLabel(info)
        self.label_people.setGeometry(QtCore.QRect(80, 300, 131, 31))
        self.label_people.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_people.setObjectName("label_people")

        # Free Seats Label
        self.label_free_seats = QtWidgets.QLabel(info)
        self.label_free_seats.setGeometry(QtCore.QRect(80, 140, 131, 31))
        self.label_free_seats.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_free_seats.setObjectName("label_free_seats")

        # Empty Session Label
        self.label_empty_session = QtWidgets.QLabel(info)
        self.label_empty_session.setGeometry(QtCore.QRect(260, 220, 321, 31))
        self.label_empty_session.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_empty_session.setText("")  # Initially empty
        self.label_empty_session.setObjectName("label_empty_session")

        # Empty Free Seats Label
        self.label_empty_free_seats = QtWidgets.QLabel(info)
        self.label_empty_free_seats.setGeometry(QtCore.QRect(260, 140, 321, 31))
        self.label_empty_free_seats.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_empty_free_seats.setText("")  # Initially empty
        self.label_empty_free_seats.setObjectName("label_empty_free_seats")

        # Empty Movie Name Label
        self.label_empty_movie_name = QtWidgets.QLabel(info)
        self.label_empty_movie_name.setGeometry(QtCore.QRect(260, 60, 321, 31))
        self.label_empty_movie_name.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_empty_movie_name.setText("")  # Initially empty
        self.label_empty_movie_name.setObjectName("label_empty_movie_name")

        # Session Label
        self.label_session = QtWidgets.QLabel(info)
        self.label_session.setGeometry(QtCore.QRect(80, 220, 131, 31))
        self.label_session.setStyleSheet("""
            color: #FFFFFF;  /* White text */
            font-size: 22px;  /* Font size */
        """)
        self.label_session.setObjectName("label_session")

        # List Widget to Show People
        self.listWidget_to_show_people = QtWidgets.QListWidget(info)
        self.listWidget_to_show_people.setGeometry(QtCore.QRect(100, 380, 421, 131))
        self.listWidget_to_show_people.setStyleSheet("""
            QListWidget {
                background-color: white;  /* White background */
                color: black;  /* Black text */
                font-size: 18px;  /* Font size */
                border-radius: 10px;  /* Rounded corners */
            }
        """)
        self.listWidget_to_show_people.setObjectName("listWidget_to_show_people")

        # Update the UI with translations
        self.retranslateUi(info)

        # Connect slots
        QtCore.QMetaObject.connectSlotsByName(info)

    def retranslateUi(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("info", "Form"))

        # Set text for all labels
        self.label_movi_name.setText(_translate("info", "Movie"))
        self.label_people.setText(_translate("info", "People"))
        self.label_free_seats.setText(_translate("info", "Free seats"))
        self.label_session.setText(_translate("info", "Session"))

        # Set a tooltip for the list widget
        self.listWidget_to_show_people.setToolTip(_translate("info", "<html><head/><body><p>kjhkj</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    info = QtWidgets.QWidget()
    ui = Ui_info()
    ui.setupUi(info)
    info.show()
    sys.exit(app.exec_())
