# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginpage(object):
    def setupUi(self, loginpage):
        loginpage.setObjectName("loginpage")
        loginpage.resize(655, 580)
        loginpage.setStyleSheet("background-color: rgb(51, 51, 51);")

        self.centralwidget = QtWidgets.QWidget(loginpage)
        self.centralwidget.setObjectName("centralwidget")

        # Поле для ввода логина
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(106, 112, 443, 55))
        self.lineEdit_login.setStyleSheet(
            """
            QLineEdit {
                border-radius: 10px;
                font-size: 20px;
                background-color: white;
                padding-left: 10px;
            }
            """
        )
        self.lineEdit_login.setPlaceholderText("Login")
        self.lineEdit_login.setObjectName("lineEdit_login")

        # Поле для ввода пароля
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(106, 200, 443, 55))
        self.lineEdit_password.setStyleSheet(
            """
            QLineEdit {
                border-radius: 10px;
                font-size: 20px;
                background-color: white;
                padding-left: 10px;
            }
            """
        )
        self.lineEdit_password.setPlaceholderText("Password")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")

        # Чекбокс "I'm not a robot"
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(110, 270, 361, 31))
        self.checkBox.setStyleSheet(
        """
        QCheckBox {
            color: white;
            font-size: 18px;
        }
        QCheckBox::indicator {
            width: 30px; 
            height: 30px; 
        }
        """
        )
        self.checkBox.setText("I'm not a robot")
        self.checkBox.setChecked(False)  # Чекбокс по умолчанию не отмечен
        self.checkBox.setObjectName("checkBox")

        # Кнопка входа
        self.pushButtonlogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonlogin.setGeometry(QtCore.QRect(187, 374, 282, 56))
        self.pushButtonlogin.setStyleSheet(
            """
            QPushButton {
                background-color: #FF0000;
                color: white;
                font-size: 18px;
                font-weight: bold;
                border-radius: 10px;
            }
            """
        )
        self.pushButtonlogin.setObjectName("pushButtonlogin")

        # Текст "New in here?"
        self.label_newinhere = QtWidgets.QLabel(self.centralwidget)
        self.label_newinhere.setGeometry(QtCore.QRect(188, 463, 131, 31))
        self.label_newinhere.setStyleSheet(
            """
            QLabel {
                color: #FFFFFF;
                font-size: 22px;
            }
            """
        )
        self.label_newinhere.setObjectName("label_newinhere")

        # Текст "Register"
        self.register_2 = QtWidgets.QLabel(self.centralwidget)
        self.register_2.setGeometry(QtCore.QRect(376, 463, 131, 31))
        self.register_2.setStyleSheet("QLabel {\n"
                                   "    color: #59ACF0;\n"
                                   "    font-size: 22px;\n"
                                   "}\n"
                                   "QLabel:hover {\n"
                                   "    text-decoration: underline;\n"
                                   "}")
        self.register_2.setText('<a style="color:white; text-decoration:none;" href="#">Register</a>')
        self.register_2.setObjectName("register_2")

        loginpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loginpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 655, 21))
        self.menubar.setObjectName("menubar")
        loginpage.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(loginpage)
        self.statusbar.setObjectName("statusbar")
        loginpage.setStatusBar(self.statusbar)

        self.retranslateUi(loginpage)
        QtCore.QMetaObject.connectSlotsByName(loginpage)

    def retranslateUi(self, loginpage):
        _translate = QtCore.QCoreApplication.translate
        loginpage.setWindowTitle(_translate("loginpage", "Login Page"))
        self.pushButtonlogin.setText(_translate("loginpage", "Log in"))
        self.label_newinhere.setText(_translate("loginpage", "New in here?"))
        # self.register_2.setText(_translate("loginpage", "Register"))


