# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seats.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_seats(object):
    def setupUi(self, seats):
        seats.setObjectName("seats")
        seats.resize(655, 580)
        seats.setStyleSheet("background-color: rgb(51, 51, 51);\n"
"font-weight: bold;\n"
"")
        self.pushButton_a1 = QtWidgets.QPushButton(seats)
        self.pushButton_a1.setGeometry(QtCore.QRect(144, 157, 23, 23))
        self.pushButton_a1.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a1.setText("")
        self.pushButton_a1.setObjectName("pushButton_a1")
        self.pushButton_6 = QtWidgets.QPushButton(seats)
        self.pushButton_6.setGeometry(QtCore.QRect(270, 35, 25, 25))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"        background-color: black;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_seats_free = QtWidgets.QLabel(seats)
        self.label_seats_free.setGeometry(QtCore.QRect(161, 30, 80, 35))
        self.label_seats_free.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_free.setObjectName("label_seats_free")
        self.label_seats_booked = QtWidgets.QLabel(seats)
        self.label_seats_booked.setGeometry(QtCore.QRect(300, 30, 101, 31))
        self.label_seats_booked.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_booked.setObjectName("label_seats_booked")
        self.label_setas_red = QtWidgets.QLabel(seats)
        self.label_setas_red.setGeometry(QtCore.QRect(470, 30, 141, 31))
        self.label_setas_red.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_setas_red.setObjectName("label_setas_red")
        self.frame_white_seats = QtWidgets.QFrame(seats)
        self.frame_white_seats.setGeometry(QtCore.QRect(130, 35, 25, 25))
        self.frame_white_seats.setStyleSheet("background-color: white;")
        self.frame_white_seats.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_white_seats.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_white_seats.setObjectName("frame_white_seats")
        self.frame_red_seats = QtWidgets.QFrame(seats)
        self.frame_red_seats.setGeometry(QtCore.QRect(434, 35, 25, 25))
        self.frame_red_seats.setStyleSheet("background-color: red\n"
";")
        self.frame_red_seats.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_red_seats.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_red_seats.setObjectName("frame_red_seats")
        self.frame_seats_screen = QtWidgets.QFrame(seats)
        self.frame_seats_screen.setGeometry(QtCore.QRect(50, 540, 571, 20))
        self.frame_seats_screen.setStyleSheet("background-color: white;\n"
"border-radius: 10px;")
        self.frame_seats_screen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seats_screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seats_screen.setObjectName("frame_seats_screen")
        self.label_screen_nadpis = QtWidgets.QLabel(self.frame_seats_screen)
        self.label_screen_nadpis.setGeometry(QtCore.QRect(240, 0, 71, 20))
        self.label_screen_nadpis.setStyleSheet("color: black;          /* Белый цвет текста */\n"
"\n"
"font-size: 15px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_screen_nadpis.setObjectName("label_screen_nadpis")
        self.label_seats_a = QtWidgets.QLabel(seats)
        self.label_seats_a.setGeometry(QtCore.QRect(80, 152, 21, 31))
        self.label_seats_a.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_a.setObjectName("label_seats_a")
        self.label_seats_1 = QtWidgets.QLabel(seats)
        self.label_seats_1.setGeometry(QtCore.QRect(148, 98, 21, 31))
        self.label_seats_1.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_1.setObjectName("label_seats_1")
        self.label_seats_b = QtWidgets.QLabel(seats)
        self.label_seats_b.setGeometry(QtCore.QRect(80, 210, 21, 31))
        self.label_seats_b.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_b.setObjectName("label_seats_b")
        self.label_seats_c = QtWidgets.QLabel(seats)
        self.label_seats_c.setGeometry(QtCore.QRect(80, 270, 21, 31))
        self.label_seats_c.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_c.setObjectName("label_seats_c")
        self.label_seats_d = QtWidgets.QLabel(seats)
        self.label_seats_d.setGeometry(QtCore.QRect(80, 325, 21, 31))
        self.label_seats_d.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_d.setObjectName("label_seats_d")
        self.pushButton_a2 = QtWidgets.QPushButton(seats)
        self.pushButton_a2.setGeometry(QtCore.QRect(210, 157, 23, 23))
        self.pushButton_a2.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a2.setText("")
        self.pushButton_a2.setObjectName("pushButton_a2")
        self.pushButton_a3 = QtWidgets.QPushButton(seats)
        self.pushButton_a3.setGeometry(QtCore.QRect(276, 157, 23, 23))
        self.pushButton_a3.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a3.setText("")
        self.pushButton_a3.setObjectName("pushButton_a3")
        self.pushButton_a4 = QtWidgets.QPushButton(seats)
        self.pushButton_a4.setGeometry(QtCore.QRect(342, 157, 23, 23))
        self.pushButton_a4.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a4.setText("")
        self.pushButton_a4.setObjectName("pushButton_a4")
        self.pushButton_a5 = QtWidgets.QPushButton(seats)
        self.pushButton_a5.setGeometry(QtCore.QRect(408, 157, 23, 23))
        self.pushButton_a5.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a5.setText("")
        self.pushButton_a5.setObjectName("pushButton_a5")
        self.pushButton_a6 = QtWidgets.QPushButton(seats)
        self.pushButton_a6.setGeometry(QtCore.QRect(474, 157, 23, 23))
        self.pushButton_a6.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a6.setText("")
        self.pushButton_a6.setObjectName("pushButton_a6")
        self.pushButton_b6 = QtWidgets.QPushButton(seats)
        self.pushButton_b6.setGeometry(QtCore.QRect(474, 214, 23, 23))
        self.pushButton_b6.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b6.setText("")
        self.pushButton_b6.setObjectName("pushButton_b6")
        self.pushButton_b1 = QtWidgets.QPushButton(seats)
        self.pushButton_b1.setGeometry(QtCore.QRect(144, 214, 23, 23))
        self.pushButton_b1.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b1.setText("")
        self.pushButton_b1.setObjectName("pushButton_b1")
        self.pushButton_b2 = QtWidgets.QPushButton(seats)
        self.pushButton_b2.setGeometry(QtCore.QRect(210, 214, 23, 23))
        self.pushButton_b2.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b2.setText("")
        self.pushButton_b2.setObjectName("pushButton_b2")
        self.pushButton_b5 = QtWidgets.QPushButton(seats)
        self.pushButton_b5.setGeometry(QtCore.QRect(408, 214, 23, 23))
        self.pushButton_b5.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b5.setText("")
        self.pushButton_b5.setObjectName("pushButton_b5")
        self.pushButton_b3 = QtWidgets.QPushButton(seats)
        self.pushButton_b3.setGeometry(QtCore.QRect(276, 214, 23, 23))
        self.pushButton_b3.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b3.setText("")
        self.pushButton_b3.setObjectName("pushButton_b3")
        self.pushButton_b4 = QtWidgets.QPushButton(seats)
        self.pushButton_b4.setGeometry(QtCore.QRect(342, 214, 23, 23))
        self.pushButton_b4.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b4.setText("")
        self.pushButton_b4.setObjectName("pushButton_b4")
        self.pushButton_a7 = QtWidgets.QPushButton(seats)
        self.pushButton_a7.setGeometry(QtCore.QRect(542, 157, 23, 23))
        self.pushButton_a7.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_a7.setText("")
        self.pushButton_a7.setObjectName("pushButton_a7")
        self.pushButton_b7 = QtWidgets.QPushButton(seats)
        self.pushButton_b7.setGeometry(QtCore.QRect(542, 214, 23, 23))
        self.pushButton_b7.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_b7.setText("")
        self.pushButton_b7.setObjectName("pushButton_b7")
        self.pushButton_c6 = QtWidgets.QPushButton(seats)
        self.pushButton_c6.setGeometry(QtCore.QRect(474, 273, 23, 23))
        self.pushButton_c6.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c6.setText("")
        self.pushButton_c6.setObjectName("pushButton_c6")
        self.pushButton_c1 = QtWidgets.QPushButton(seats)
        self.pushButton_c1.setGeometry(QtCore.QRect(144, 273, 23, 23))
        self.pushButton_c1.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c1.setText("")
        self.pushButton_c1.setObjectName("pushButton_c1")
        self.pushButton_c2 = QtWidgets.QPushButton(seats)
        self.pushButton_c2.setGeometry(QtCore.QRect(210, 273, 23, 23))
        self.pushButton_c2.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c2.setText("")
        self.pushButton_c2.setObjectName("pushButton_c2")
        self.pushButton_d1 = QtWidgets.QPushButton(seats)
        self.pushButton_d1.setGeometry(QtCore.QRect(144, 330, 23, 23))
        self.pushButton_d1.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d1.setText("")
        self.pushButton_d1.setObjectName("pushButton_d1")
        self.pushButton_d5 = QtWidgets.QPushButton(seats)
        self.pushButton_d5.setGeometry(QtCore.QRect(408, 330, 23, 23))
        self.pushButton_d5.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d5.setText("")
        self.pushButton_d5.setObjectName("pushButton_d5")
        self.pushButton_d6 = QtWidgets.QPushButton(seats)
        self.pushButton_d6.setGeometry(QtCore.QRect(474, 330, 23, 23))
        self.pushButton_d6.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d6.setText("")
        self.pushButton_d6.setObjectName("pushButton_d6")
        self.pushButton_c5 = QtWidgets.QPushButton(seats)
        self.pushButton_c5.setGeometry(QtCore.QRect(408, 273, 23, 23))
        self.pushButton_c5.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c5.setText("")
        self.pushButton_c5.setObjectName("pushButton_c5")
        self.pushButton_c3 = QtWidgets.QPushButton(seats)
        self.pushButton_c3.setGeometry(QtCore.QRect(276, 273, 23, 23))
        self.pushButton_c3.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c3.setText("")
        self.pushButton_c3.setObjectName("pushButton_c3")
        self.pushButton_c4 = QtWidgets.QPushButton(seats)
        self.pushButton_c4.setGeometry(QtCore.QRect(342, 273, 23, 23))
        self.pushButton_c4.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c4.setText("")
        self.pushButton_c4.setObjectName("pushButton_c4")
        self.pushButton_d3 = QtWidgets.QPushButton(seats)
        self.pushButton_d3.setGeometry(QtCore.QRect(276, 330, 23, 23))
        self.pushButton_d3.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d3.setText("")
        self.pushButton_d3.setObjectName("pushButton_d3")
        self.pushButton_d4 = QtWidgets.QPushButton(seats)
        self.pushButton_d4.setGeometry(QtCore.QRect(342, 330, 23, 23))
        self.pushButton_d4.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d4.setText("")
        self.pushButton_d4.setObjectName("pushButton_d4")
        self.pushButton_c7 = QtWidgets.QPushButton(seats)
        self.pushButton_c7.setGeometry(QtCore.QRect(542, 273, 23, 23))
        self.pushButton_c7.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_c7.setText("")
        self.pushButton_c7.setObjectName("pushButton_c7")
        self.pushButton_d7 = QtWidgets.QPushButton(seats)
        self.pushButton_d7.setGeometry(QtCore.QRect(542, 330, 23, 23))
        self.pushButton_d7.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d7.setText("")
        self.pushButton_d7.setObjectName("pushButton_d7")
        self.pushButton_d2 = QtWidgets.QPushButton(seats)
        self.pushButton_d2.setGeometry(QtCore.QRect(210, 330, 23, 23))
        self.pushButton_d2.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_d2.setText("")
        self.pushButton_d2.setObjectName("pushButton_d2")
        self.label_seats_2 = QtWidgets.QLabel(seats)
        self.label_seats_2.setGeometry(QtCore.QRect(210, 98, 21, 31))
        self.label_seats_2.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_2.setObjectName("label_seats_2")
        self.label_seats_6 = QtWidgets.QLabel(seats)
        self.label_seats_6.setGeometry(QtCore.QRect(474, 98, 21, 31))
        self.label_seats_6.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_6.setObjectName("label_seats_6")
        self.label_seats_3 = QtWidgets.QLabel(seats)
        self.label_seats_3.setGeometry(QtCore.QRect(276, 98, 21, 31))
        self.label_seats_3.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_3.setObjectName("label_seats_3")
        self.label_seats_5 = QtWidgets.QLabel(seats)
        self.label_seats_5.setGeometry(QtCore.QRect(408, 98, 21, 31))
        self.label_seats_5.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_5.setObjectName("label_seats_5")
        self.label_seats_4 = QtWidgets.QLabel(seats)
        self.label_seats_4.setGeometry(QtCore.QRect(342, 98, 21, 31))
        self.label_seats_4.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_4.setObjectName("label_seats_4")
        self.label_seats_7 = QtWidgets.QLabel(seats)
        self.label_seats_7.setGeometry(QtCore.QRect(542, 98, 21, 31))
        self.label_seats_7.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_7.setObjectName("label_seats_7")
        self.label_seats_f = QtWidgets.QLabel(seats)
        self.label_seats_f.setGeometry(QtCore.QRect(80, 380, 21, 31))
        self.label_seats_f.setStyleSheet("color: #FFFFFF;          /* Белый цвет текста */\n"
"\n"
"font-size: 20px;         /* Размер шрифта */\n"
"     /* Жирный шрифт */\n"
"")
        self.label_seats_f.setObjectName("label_seats_f")
        self.pushButton_f7 = QtWidgets.QPushButton(seats)
        self.pushButton_f7.setGeometry(QtCore.QRect(542, 387, 23, 23))
        self.pushButton_f7.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f7.setText("")
        self.pushButton_f7.setObjectName("pushButton_f7")
        self.pushButton_f5 = QtWidgets.QPushButton(seats)
        self.pushButton_f5.setGeometry(QtCore.QRect(408, 387, 23, 23))
        self.pushButton_f5.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f5.setText("")
        self.pushButton_f5.setObjectName("pushButton_f5")
        self.pushButton_f6 = QtWidgets.QPushButton(seats)
        self.pushButton_f6.setGeometry(QtCore.QRect(474, 387, 23, 23))
        self.pushButton_f6.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f6.setText("")
        self.pushButton_f6.setObjectName("pushButton_f6")
        self.pushButton_f3 = QtWidgets.QPushButton(seats)
        self.pushButton_f3.setGeometry(QtCore.QRect(276, 387, 23, 23))
        self.pushButton_f3.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f3.setText("")
        self.pushButton_f3.setObjectName("pushButton_f3")
        self.pushButton_f4 = QtWidgets.QPushButton(seats)
        self.pushButton_f4.setGeometry(QtCore.QRect(342, 387, 23, 23))
        self.pushButton_f4.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f4.setText("")
        self.pushButton_f4.setObjectName("pushButton_f4")
        self.pushButton_f2 = QtWidgets.QPushButton(seats)
        self.pushButton_f2.setGeometry(QtCore.QRect(210, 387, 23, 23))
        self.pushButton_f2.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f2.setText("")
        self.pushButton_f2.setObjectName("pushButton_f2")
        self.pushButton_f1 = QtWidgets.QPushButton(seats)
        self.pushButton_f1.setGeometry(QtCore.QRect(144, 387, 23, 23))
        self.pushButton_f1.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        \n"
"}\n"
"")
        self.pushButton_f1.setText("")
        self.pushButton_f1.setObjectName("pushButton_f1")

        self.retranslateUi(seats)
        QtCore.QMetaObject.connectSlotsByName(seats)

    def retranslateUi(self, seats):
        _translate = QtCore.QCoreApplication.translate
        seats.setWindowTitle(_translate("seats", "Form"))
        self.label_seats_free.setText(_translate("seats", "- Free"))
        self.label_seats_booked.setText(_translate("seats", "- Booked"))
        self.label_setas_red.setText(_translate("seats", "- Your spot"))
        self.label_screen_nadpis.setText(_translate("seats", "SCREEN"))
        self.label_seats_a.setText(_translate("seats", "A"))
        self.label_seats_1.setText(_translate("seats", "1"))
        self.label_seats_b.setText(_translate("seats", "B"))
        self.label_seats_c.setText(_translate("seats", "C"))
        self.label_seats_d.setText(_translate("seats", "D"))
        self.label_seats_2.setText(_translate("seats", "2"))
        self.label_seats_6.setText(_translate("seats", "6"))
        self.label_seats_3.setText(_translate("seats", "3"))
        self.label_seats_5.setText(_translate("seats", "5"))
        self.label_seats_4.setText(_translate("seats", "4"))
        self.label_seats_7.setText(_translate("seats", "7"))
        self.label_seats_f.setText(_translate("seats", "F"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    seats = QtWidgets.QWidget()
    ui = Ui_seats()
    ui.setupUi(seats)
    seats.show()
    sys.exit(app.exec_())
